# version: '3'

# services:
#   web:
#     image: php8.1-apache:projet
#     container_name: projet-php-apache
#     ports:
#       # local:container
#       - "1337:80"
#     environment: 
#       - APACHE_DOCUMENT_ROOT=/var/www/html
#       - COMPOSER_ALLOW_SUPERUSER=1
#     volumes:
#       # Volume stockant les fichiers web du projet
#       - ./:/var/www/html
#     build:
#       context: .
#       dockerfile: dockerfile
#     depends_on:
#       - db
#     links:
#       # Lien vers le conteneur "db" (déclaré ci-après)
#       - db:db

#   pma:
#     image: phpmyadmin
#     container_name: projet-phpmyadmin
#     environment:
#       # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
#       PMA_HOST: db
#       PMA_PORT: 3306
#       UPLOAD_LIMIT: 1024M
#     ports:
#       - "8080:80"
#     links:
#       - db:db

#   db:
#     image: mariadb:latest
#     container_name: projet-mysql
#     ports:
#       - "3306:3306"
#     volumes:
#       # Volume de la base de données
#       - ./db-data:/var/lib/mysql
#     environment:
#       MYSQL_DATABASE: test
#       # MYSQL_ROOT_PASSWORD: XXXXXXXXX
#       MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#       # MARIADB_RANDOM_ROOT_PASSWORD: "yes"


version: '3.9'

services:
    php:
      build: ./config/php
      ports:
        - "81:80" 
        # 80:80, http
        # mon PC:machine virtuelle
        - "443:443"
        # le port 443 est pour le https
      volumes:
        - ./back:/var/www/html 
      env_file:
        - ./.env
    db:
      image: mariadb
      restart: always
#      env_file:
#        - ./.env
      ports:
        - "3307:3306"
      volumes:
        - db:/var/lib/mariadb

    node:
      build: ./config/node
      working_dir: /var/nodeJS
      ports:
        - "3000:3000"
      volumes:
        - ./front:/var/nodeJS

volumes:
  db: